package multiply3;

import java.util.*;

public class Multiply3Test {
    
    static int number1;
    static int number2;
    static int answer;
    static int input;
    static int guess;
    static int totalCorrect = 0;
    static int totalQuestions = 0;
    static String response; 
    static Random randomNumber = new Random();
    static int[][] retainer = new int [99][4];
    
     public static void quiz(){
         
         while (guess != -1) {
             createQuestion();
             checkResponse();
         }
         
         totalQuestions--;
         
         if (totalQuestions > 0) {
             printQuestionResult();
         } else {
             System.out.println("You didn't answer any questions");
         }
     }
     
     public static void createQuestion(){
         Scanner input = new Scanner(System.in);
         number1 = randomNumber.nextInt(10);// genrate random numbers between 0-9
         number2 = randomNumber.nextInt(10);// genrate random numbers between 0-9
         answer = number1 * number2;//calculates answer
         
         System.out.println("How much is "+number1+" times "
                +number2+"?"+
                 "\nEnter your answer (-1 to exit)");
         guess = input.nextInt();
         
         if (guess!= -1){
             retainer[totalQuestions][0] = number1;
             retainer[totalQuestions][1] = number2;
             retainer[totalQuestions][2] = guess;
             retainer[totalQuestions][3] = answer;
         }
     }
     
     public static String createResponse(boolean correct){
      
      if (correct) { 
      
        switch (randomNumber.nextInt(4)+1) {
             case 1: return response = ("Very good!\n");
                               
             case 2: return response = ("Excellent!\n");
                 
             case 3: return response = ("Nice work!\n");
                 
             case 4: return response = ("Keep up the good work!\n");
                
          }
    }       
   
              switch (randomNumber.nextInt(4)+1){
             case 1: return response = ("No. Please try again.\n");
                 
             case 2: return response = ("Wrong. Try once more.\n");
                 
             case 3: return response = ("Don't give up!\n");
                 
             case 4: return response = ("No. Keep trying.\n");
             
         }
     
        return response;
 }
     
     public static void checkResponse(){
         
         totalQuestions++;
         
         if (answer == guess){
            
             totalCorrect++; 
            System.out.println(createResponse(true));
             
         }else{
             
             System.out.println(createResponse(false));
             System.out.println("The correct answer is "+answer+".\n");
         }
     
     }
     
     public static void printQuestionResult(){
         System.out.println("The questions generated by the system are:");
 
         for (int i = 0; i < totalQuestions; i++) {
          
             if(retainer[i][2] == retainer[i][3]) {
             System.out.println(retainer[i][0]+" * "+retainer[i][1]+" = "+retainer[i][3]);
         }
         else
         {
            System.out.println(retainer[i][0]+" * "+retainer[i][1]+" = "+retainer[i][3]+
                    ", You answered "+retainer[i][2]+" which is incorrect.");   
         }
      }
         
         System.out.println("You got "+totalCorrect+" question correct out of "+totalQuestions+" questions");
     
         if (totalCorrect > (totalQuestions - totalCorrect)){
             System.out.println(createResponse(true)+"\n");
         } else{
             System.out.println(createResponse(false)+"\n");
         }
     
     
     
     }
}

